name: CMake
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DBUILD_UNIT_TESTS="True"

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Debug

      - name: Test
        working-directory: ${{github.workspace}}/build/src/test
        run: ls -alh && ctest -C Debug

  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Run
        working-directory: ${{github.workspace}}/build
        run: ls -alh && make ci_cd_hello_world && ./ci_cd_hello_world