name: Pipeline

permissions:
  checks: write
  contents: write
  pull-requests: write # only required if `comment: true` was enabled

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DBUILD_UNIT_TESTS="True"

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Debug

      - name: Test
        working-directory: ${{github.workspace}}/build/src/test
        run: ctest --version && ctest -C Debug --extra-verbose --output-junit ./test-result.xml

      - name: Test Report
        uses: mikepenz/action-junit-report@v5
        if: (success() || failure())
        with:
          report_paths: '${{github.workspace}}/build/src/test/test-result.xml'
          comment: true
          updateComment: true
          include_passed: true

      - name: Install Gcovr
        run: pipx install gcovr

      - name: Coverage HTML
        working-directory: ${{github.workspace}}
        run: mkdir cov-report && gcovr -f src/main -r . --html-details -o cov-report/index.html --print-summary

      - name: Coverage cobertura
        working-directory: ${{github.workspace}}
        run: gcovr -f src/main -r . --cobertura-pretty --cobertura cov-report/cobertura-coverage.xml

      - name: Generate Badge
        if: (success() || failure()) && github.ref == 'refs/heads/master'
        uses: cjlapao/simple-badge-generator-action@v1
        with:
          badge-path: '${{github.workspace}}/cov-report/coverage.svg'
          badge-type: 'cobertura'
          title: 'Coverage'
          cobertura-path: '${{github.workspace}}/cov-report/cobertura-coverage.xml'

      - name: Coverage Report
        if: (success() || failure()) && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: cov-report

  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Run
        working-directory: ${{github.workspace}}/build/src/main
        run: make ci_cd_hello_world &&  ls -alh && ./ci_cd_hello_world